max_width = 88
style_edition = "2024"
hard_tabs = false

format_code_in_doc_comments = true
format_macro_bodies = true
format_strings = true
imports_granularity = "Module"
comment_width = 88
normalize_doc_attributes = true
reorder_impl_items = true
format_macro_matchers = false
normalize_comments = true
wrap_comments = true
