format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = false
format_strings = true
imports_granularity = "Module"
max_width = 88
normalize_doc_attributes = true
reorder_impl_items = true
unstable_features = false
style_edition = "2024"
